# Generated by Django 5.2.6 on 2026-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'verbose_name_plural': 'Case studies'},
        ),
    ]
