"""
Django settings for awareness_portal project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer environment variable in production; fall back to a development key for local dev/tests
_DEFAULT_DEV_SECRET = "django-insecure-z*+!u@8f40(uh6nwck2y&75iv7%6f!jjcmm6ff53rg=+u5g=_y"
SECRET_KEY = os.environ.get("AWARENESS_SECRET_KEY", _DEFAULT_DEV_SECRET)

# If running in production (DEBUG=False), require an explicit SECRET_KEY via env var
if not (os.environ.get("AWARENESS_DEBUG", "True").lower() in ("1", "true", "yes")):
    if SECRET_KEY == _DEFAULT_DEV_SECRET:
        raise RuntimeError(
            "AWARENESS_SECRET_KEY must be set in production (DEBUG=False)"
        )

# Toggle debug using environment variable. Default to True for development convenience.
DEBUG = os.environ.get("AWARENESS_DEBUG", "True").lower() in ("1", "true", "yes")

# ALLOWED_HOSTS should be set in production via AWARENESS_ALLOWED_HOSTS (comma-separated)
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("AWARENESS_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_yasg",
    "corsheaders",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "modeltranslation",
    # Local apps
    "authentication",
    "dashboard",
    "policy",
    "training",
    "quizzes",
    "case_studies",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise should be just after SecurityMiddleware to serve static files efficiently
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS middleware (must be before CommonMiddleware)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # OTP middleware for 2FA
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # CSP middleware for security headers
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = "awareness_portal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "awareness_portal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Allow overriding the database with a DATABASE_URL environment variable (e.g. postgres://...)
try:
    import dj_database_url

    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES["default"] = dict(dj_database_url.parse(DATABASE_URL, conn_max_age=600))
except Exception:
    # dj-database-url is optional; keep sqlite default if not available
    pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication backends (SAML, LDAP, standard Django)
AUTHENTICATION_BACKENDS = [
    'authentication.saml_backend.SAMLAuthenticationBackend',
    'authentication.saml_backend.LDAPAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
]

# SAML 2.0 SSO Configuration
SAML_ENABLED = os.environ.get('SAML_ENABLED', 'False').lower() == 'true'
SAML_FOLDER = os.path.join(BASE_DIR, 'saml')  # Folder for SAML settings.json and certs
SAML_IDP_METADATA_URL = os.environ.get('SAML_IDP_METADATA_URL', '')

# LDAP/Active Directory Configuration
try:
    import importlib

    ldap = importlib.import_module('ldap')
    ldap_config = importlib.import_module('django_auth_ldap.config')
    LDAPSearch = ldap_config.LDAPSearch
    
    AUTH_LDAP_SERVER_URI = os.environ.get('LDAP_SERVER_URI', 'ldap://localhost')
    AUTH_LDAP_BIND_DN = os.environ.get('LDAP_BIND_DN', '')
    AUTH_LDAP_BIND_PASSWORD = os.environ.get('LDAP_BIND_PASSWORD', '')
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        os.environ.get('LDAP_USER_DN', 'ou=users,dc=example,dc=com'),
        ldap.SCOPE_SUBTREE,
        '(uid=%(user)s)'
    )
    
    # Map LDAP attributes to Django user model
    AUTH_LDAP_USER_ATTR_MAP = {
        'first_name': 'givenName',
        'last_name': 'sn',
        'email': 'mail',
    }
    
    # Auto-create users from LDAP
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
except ImportError:
    # LDAP support is optional
    pass


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use WhiteNoise compressed manifest storage in production to enable long-term caching
STATICFILES_STORAGE = os.environ.get(
    "AWARENESS_STATICFILES_STORAGE",
    "whitenoise.storage.CompressedManifestStaticFilesStorage",
)

# Authentication redirects
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/dashboard/"

# Email configuration
EMAIL_BACKEND = os.environ.get(
    "AWARENESS_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Default from email
DEFAULT_FROM_EMAIL = os.environ.get(
    "AWARENESS_DEFAULT_FROM_EMAIL", "awareness-portal@company.com"
)
SECURITY_TEAM_EMAIL = os.environ.get(
    "SECURITY_TEAM_EMAIL", "security-ops@company.com"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Security settings (sensible defaults; override in production-specific settings) ---
if not DEBUG:
    # Redirect all non-HTTPS to HTTPS when not in debug
    SECURE_SSL_REDIRECT = os.environ.get(
        "AWARENESS_SECURE_SSL_REDIRECT", "True"
    ).lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS: enable for production (set to a non-zero integer in seconds)
    SECURE_HSTS_SECONDS = int(os.environ.get("AWARENESS_SECURE_HSTS_SECONDS", 60))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get(
        "AWARENESS_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
    ).lower() in ("1", "true", "yes")
    SECURE_HSTS_PRELOAD = os.environ.get(
        "AWARENESS_SECURE_HSTS_PRELOAD", "False"
    ).lower() in ("1", "true", "yes")
else:
    # Development: allow cookies over HTTP and set samesite for local testing
    SESSION_COOKIE_SECURE = False  # WARNING: Do not use in production
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False

# CSRF trusted origins (comma separated)
_csrf_trusted_origins = os.environ.get("AWARENESS_CSRF_TRUSTED_ORIGINS")
if _csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = [
        x.strip()
        for x in _csrf_trusted_origins.split(",")
        if x.strip()
    ]

# Basic logging configuration — override or extend in production if desired
LOG_LEVEL = os.environ.get("AWARENESS_LOG_LEVEL", "DEBUG")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django.contrib.sessions": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.contrib.auth": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Allow simple access to the logger in other modules
logger = logging.getLogger(__name__)

# Cache configuration (use Redis for production, fallback to in-memory for dev)
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL and not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'awareness',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'awareness-cache',
        }
    }

# ML Configuration (Production-ready, enabled by default)
ML_ENABLED = os.environ.get('ML_ENABLED', 'True').lower() in ('1', 'true', 'yes')
ML_MODEL_VERSION = os.environ.get('ML_MODEL_VERSION', '1.0')
ML_MODEL_DIR = Path(os.environ.get('ML_MODEL_DIR', str(BASE_DIR / 'ml_models')))
ML_STRICT_READINESS = os.environ.get('ML_STRICT_READINESS', 'False').lower() in ('1', 'true', 'yes')
ML_MIN_LABELS = int(os.environ.get('ML_MIN_LABELS', '50'))
ML_MIN_POSITIVE_LABELS = int(os.environ.get('ML_MIN_POSITIVE_LABELS', '10'))
ML_MIN_NEGATIVE_LABELS = int(os.environ.get('ML_MIN_NEGATIVE_LABELS', '10'))

# Rate Limiting Configuration
GLOBAL_RATE_LIMIT = int(os.environ.get('GLOBAL_RATE_LIMIT', '1000'))
GLOBAL_RATE_LIMIT_WINDOW = int(os.environ.get('GLOBAL_RATE_LIMIT_WINDOW', '60'))

# Celery Configuration (for async processing)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# GDPR Configuration
GDPR_RETENTION_DAYS = int(os.environ.get('GDPR_RETENTION_DAYS', str(365 * 7)))  # 7 years default

# =============================================================================
# REST Framework Configuration
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Swagger/OpenAPI Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'patch', 'delete'],
}

# =============================================================================
# CORS Configuration
# =============================================================================

# Allow CORS from specific origins (configure for production)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =============================================================================
# Security Headers & CSP
# =============================================================================

# Content Security Policy
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'",)

# Additional Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# Sentry Error Tracking (Production)
# =============================================================================

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=0.1,
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
    )

# =============================================================================
# Internationalization & Localization
# =============================================================================

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Modeltranslation settings
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_LANGUAGES = ('en', 'fr', 'ar')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en',)

# =============================================================================
# Notification Settings
# =============================================================================

# Slack Integration
SLACK_WEBHOOK_URL = os.environ.get('SLACK_WEBHOOK_URL', '')
SLACK_CHANNEL = os.environ.get('SLACK_CHANNEL', '#security-alerts')

# Microsoft Teams Integration
TEAMS_WEBHOOK_URL = os.environ.get('TEAMS_WEBHOOK_URL', '')

# =============================================================================
# Search Configuration (Elasticsearch - Optional)
# =============================================================================

# Only configure Elasticsearch if packages are installed
try:
    import elasticsearch
    import elasticsearch_dsl
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': os.environ.get('ELASTICSEARCH_URL', 'localhost:9200'),
            'http_auth': (
                os.environ.get('ELASTICSEARCH_USER', ''),
                os.environ.get('ELASTICSEARCH_PASSWORD', ''),
            ) if os.environ.get('ELASTICSEARCH_USER') else None,
        },
    }
except ImportError:
    # Elasticsearch not installed - search features disabled
    ELASTICSEARCH_DSL = None

# =============================================================================
# File Upload & Storage
# =============================================================================

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# AWS S3 Configuration (optional, for production file storage)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')

# =============================================================================
# Performance & Optimization
# =============================================================================

# Database Connection Pooling
CONN_MAX_AGE = 600  # 10 minutes

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = False

# =============================================================================
# Testing Configuration
# =============================================================================

if 'test' in sys.argv:
    # Speed up tests
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]
    
    # Use in-memory database for tests
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

