"""Auto-generated migration to add attempt_limit and QuizResponse.

Generated by assistant to keep test DB in sync with models.py.
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_limit',
            field=models.PositiveIntegerField(help_text='Optional per-user attempt limit', null=True, blank=True),
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice')),
            ],
        ),
    ]
