# Generated by Django 5.2.6 on 2026-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_add_attemptlimit_and_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name_plural': 'Quiz attempts'},
        ),
        migrations.AlterModelOptions(
            name='quizresponse',
            options={'verbose_name_plural': 'Quiz responses'},
        ),
    ]
