# Generated by Django 5.2.10 on 2026-01-30 12:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='policy.policy')),
            ],
            options={
                'ordering': ('policy', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('left_operand', models.CharField(max_length=512)),
                ('operator', models.CharField(choices=[('==', 'equals'), ('!=', 'not_equals'), ('>', 'gt'), ('<', 'lt'), ('>=', 'gte'), ('<=', 'lte'), ('in', 'in'), ('not_in', 'not_in'), ('regex', 'regex')], max_length=16)),
                ('right_value', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='policy.control')),
            ],
            options={
                'ordering': ('control', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_type', models.CharField(choices=[('count', 'Count'), ('percent', 'Percent'), ('time_window', 'TimeWindow')], max_length=32)),
                ('value', models.FloatField(help_text='Primary threshold value (meaning depends on type)')),
                ('window_seconds', models.PositiveIntegerField(blank=True, help_text='Window duration for time-based thresholds', null=True)),
                ('control', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='policy.control')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('evidence', models.JSONField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='policy.control')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='policy.policy')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='policy.rule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='HumanLayerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('auth', 'Authentication'), ('quiz', 'Quiz'), ('training', 'Training'), ('admin', 'Admin'), ('other', 'Other')], default='other', max_length=32)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(help_text='Explainable structured payload for forensic review')),
                ('related_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='policy.control')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='policy.policy')),
                ('related_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='policy.violation')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='policy.policy')),
                ('violation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_obj', to='policy.violation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
