# Generated by Django 5.2.10 on 2026-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_humanlayerevent_processed_violation_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='combination',
            field=models.CharField(choices=[('any', 'Any'), ('all', 'All')], default='any', help_text='How to combine rule results: any=OR, all=AND', max_length=8),
        ),
        migrations.AddField(
            model_name='policy',
            name='version',
            field=models.CharField(default='1.0', max_length=64),
        ),
    ]
