# Generated by Django 5.2.10 on 2026-01-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_experiment_control_expression_detectionmetric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyhistory',
            options={'permissions': (('export_evidence', 'Can export evidence'),)},
        ),
        migrations.AddField(
            model_name='humanlayerevent',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='humanlayerevent',
            name='signature',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('active', 'Active'), ('retired', 'Retired')], default='draft', help_text='Policy lifecycle state', max_length=16),
        ),
        migrations.AddField(
            model_name='violation',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='expression',
            field=models.JSONField(blank=True, help_text='Optional composite boolean expression over rule names or ids', null=True),
        ),
        migrations.CreateModel(
            name='ExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=200)),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ScorerArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sha256', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
