# Generated by Django 5.2.6 on 2026-02-02 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_append_only_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledge', 'Acknowledge'), ('resolve', 'Resolve'), ('reopen', 'Reopen'), ('escalate', 'Escalate'), ('comment', 'Comment')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, help_text='Optional metadata for this action', null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='policyhistory',
            options={'ordering': ('-created_at',), 'permissions': (('export_evidence', 'Can export evidence'),)},
        ),
        migrations.AddField(
            model_name='policy',
            name='notification_channel',
            field=models.CharField(blank=True, help_text='Email, webhook, or channel for violation notifications', max_length=200),
        ),
        migrations.AddField(
            model_name='policy',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='SLA response time in hours', null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', help_text='Policy lifecycle state', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('lifecycle', 'active')), fields=('name', 'lifecycle'), name='unique_active_policy_per_name'),
        ),
        migrations.AddField(
            model_name='violationactionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationactionlog',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_log', to='policy.violation'),
        ),
    ]
