# Generated by Django 5.2.6 on 2026-02-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_policy_lifecycle_and_action_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMetadata',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='policy.humanlayerevent')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('prev_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('tsa_token', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_eventmetadata',
            },
        ),
        migrations.RemoveField(
            model_name='humanlayerevent',
            name='prev_hash',
        ),
        migrations.RemoveField(
            model_name='humanlayerevent',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='humanlayerevent',
            name='signature',
        ),
    ]
