# Generated by Django 5.2.10 on 2026-02-03 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_event_metadata_separation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ('policy', 'order', 'id'), 'verbose_name_plural': 'Controls'},
        ),
        migrations.AlterModelOptions(
            name='eventmetadata',
            options={'verbose_name': 'Event metadata', 'verbose_name_plural': 'Event metadata'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ('-created_at',), 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidence'},
        ),
        migrations.AlterModelOptions(
            name='groundtruthlabel',
            options={'ordering': ('-event__timestamp',), 'verbose_name_plural': 'Ground truth labels'},
        ),
        migrations.AlterModelOptions(
            name='humanlayerevent',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'Human layer events'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyhistory',
            options={'ordering': ('-created_at',), 'permissions': (('export_evidence', 'Can export evidence'),), 'verbose_name_plural': 'Policy history'},
        ),
        migrations.AlterModelOptions(
            name='violationactionlog',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'Violation action logs'},
        ),
        migrations.CreateModel(
            name='GDPRDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID of deleted user (preserved for audit)')),
                ('username', models.CharField(help_text='Username at time of deletion', max_length=150)),
                ('email', models.EmailField(help_text='Email at time of deletion', max_length=254)),
                ('deleted_at', models.DateTimeField(db_index=True)),
                ('violations_count', models.IntegerField(default=0)),
                ('events_count', models.IntegerField(default=0)),
                ('reason', models.TextField(help_text='Reason for deletion (e.g., GDPR Right to Erasure)')),
                ('confirmation_code', models.CharField(help_text='Unique confirmation code for verification', max_length=64, unique=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_deletions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GDPR deletion log',
                'verbose_name_plural': 'GDPR deletion logs',
                'ordering': ('-deleted_at',),
            },
        ),
        migrations.CreateModel(
            name='ImmutabilityBypassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('record_id', models.CharField(help_text='Primary key of target record', max_length=128)),
                ('operation', models.CharField(choices=[('update', 'Update Attempt'), ('delete', 'Delete Attempt'), ('bulk_update', 'Bulk Update Attempt'), ('bulk_delete', 'Bulk Delete Attempt')], max_length=32)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False, help_text='Whether bypass was successful')),
                ('details', models.JSONField(blank=True, help_text='Additional context about the attempt', null=True)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Immutability bypass log',
                'verbose_name_plural': 'Immutability bypass logs',
                'ordering': ('-attempted_at',),
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='policy_immu_model_n_a16ed9_idx'), models.Index(fields=['attempted_by', 'attempted_at'], name='policy_immu_attempt_91120b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(help_text='Model name (Evidence, HumanLayerEvent, etc.)', max_length=64)),
                ('record_id', models.CharField(help_text='Primary key of rotated record', max_length=128)),
                ('old_signature', models.TextField(help_text='Original signature before rotation')),
                ('new_signature', models.TextField(help_text='New signature after rotation')),
                ('key_version', models.IntegerField(help_text='New key version number')),
                ('rotated_at', models.DateTimeField(db_index=True)),
                ('rotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key rotation log',
                'verbose_name_plural': 'Key rotation logs',
                'ordering': ('-rotated_at',),
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='policy_keyr_record__c06a8d_idx')],
            },
        ),
    ]
