# Generated by Django 5.2.6 on 2026-04-17 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_alter_control_options_alter_eventmetadata_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Policy version attested to', max_length=64)),
                ('attested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='policy.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_attestations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy attestation',
                'verbose_name_plural': 'Policy attestations',
                'ordering': ('-attested_at',),
                'indexes': [models.Index(fields=['user', 'policy'], name='policy_poli_user_id_91ff58_idx'), models.Index(fields=['attested_at'], name='policy_poli_atteste_be7dce_idx')],
                'unique_together': {('user', 'policy', 'version')},
            },
        ),
    ]
