# Generated by Django 5.2.6 on 2026-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogress',
            options={'ordering': ['-completed_at'], 'verbose_name_plural': 'Training progress'},
        ),
    ]
